version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile_website

  backend:
    build:
      context: .
      dockerfile: Dockerfile_scraper

    ports:
      - "3002:3002"
